[tool.poetry]
name = "housemanagement"
version = "0.1.0"
description = ""
authors = ["GakmanNN <gnn87@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
Django = "^4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
